# Generated by Django 4.2 on 2023-06-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("color", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="image_products"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Name",
        ),
        migrations.CreateModel(
            name="KeyboardSpecs",
            fields=[
                (
                    "productspecs_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.productspecs",
                    ),
                ),
                ("keyboard_type", models.CharField(max_length=15)),
                (
                    "switches_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "switches_img",
                    models.ImageField(blank=True, null=True, upload_to="switches_img"),
                ),
                ("lubricated", models.BooleanField()),
            ],
            bases=("core.productspecs",),
        ),
        migrations.CreateModel(
            name="SwitchesSpecs",
            fields=[
                (
                    "productspecs_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.productspecs",
                    ),
                ),
                ("switches_type", models.CharField(max_length=20)),
                (
                    "switches_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "switches_img",
                    models.ImageField(blank=True, null=True, upload_to="switches_img"),
                ),
                ("lubricated", models.BooleanField()),
            ],
            bases=("core.productspecs",),
        ),
    ]
