# Generated by Django 4.2.2 on 2023-06-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_photo_remove_productspecs_image_productspecs_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="product",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
            preserve_default=False,
        ),
    ]
