# Generated by Django 4.2.2 on 2023-06-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_photo_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="product",
        ),
        migrations.CreateModel(
            name="ProductSpecsPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.photo"
                    ),
                ),
                (
                    "productspecs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productspecs",
                    ),
                ),
            ],
        ),
    ]
