# Generated by Django 4.2.2 on 2023-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
    ]
