# Generated by Django 4.2.2 on 2023-07-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_cart_purchased"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
